set -g @plugin 'ChrisJohnsen/tmux-MacOSX-pasteboard'
set -g prefix C-x
unbind C-b
bind C-x send-prefix
#set swap pane key
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R
set-option -g mouse on
setw -g mode-keys vi
# history
set -g history-limit 200000

# faster response
set -sg escape-time 0

# reduce lag
set -g assume-paste-time 0

# terminal
set -g default-terminal "tmux-256color"
